jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee
=> OC-10527 Add OC Item Group to Form Designer

.travis.yml, dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, hub/actions.py, jsapp/js/assetParserUtils.es6, jsapp/js/components/modalForms/projectSettings.es6, jsapp/js/constants.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/mixins.es6, jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, kpi/deployment_backends/kobocat_backend.py, kpi/models/asset.py
=> OC-10528 & OC-10670 & OC-10714

jsapp/js/editorMixins/editableForm.es6, jsapp/xlform/src/view.row.coffee
=> OC-10773 & OC-10765

jsapp/js/components/RESTServices/RESTServicesList.es6, jsapp/js/components/drawer.es6, jsapp/js/components/formLanding.es6, jsapp/js/components/formSummary.es6, jsapp/js/components/header.es6, jsapp/js/components/modalForms/copyTeamPermissions.es6, jsapp/js/components/modalForms/projectSettings.es6, jsapp/js/constants.es6, jsapp/js/mixins.es6
=> OC-10868 Ensure terminology match

jsapp/js/editorMixins/editableForm.es6, jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, kpi/models/asset.py
=> OC-11720, OC-11733, OC-11738, OC-11739

jsapp/js/actions.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.rowSelector.coffee
=> OC-11740, OC-11742, OC-11732, OC-11797

jsapp/js/editorMixins/editableForm.es6, jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.icons.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.surveyApp.coffee
=> OC-11801, OC-11861, OC-11862, OC-11886, OC-11885, OC-11907

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, jsapp/js/components/list.es6, jsapp/js/editorMixins/assetNavigator.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/main.es6, jsapp/js/utils.es6, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/mv.validationLogicHelpers.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.rowSelector.coffee, jsapp/xlform/src/view.rowSelector.templates.coffee, kobo/settings/base.py, kpi/filters.py, kpi/models/asset.py
=> OC-11906, OC-11942, OC-11943, OC-11949, OC-11962, OC-11963, OC-11937, OC-11941

jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.rowSelector.coffee
=> OC-12010, OC-12038

jsapp/xlform/src/view.rowDetail.coffee, kobo/settings/base.py
=> OC-11801, OC-11941

jsapp/js/main.es6, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.rowSelector.templates.coffee
=> OC-11964, OC-12104, OC-12079, OC-12017

jsapp/js/constants.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/utils.es6, jsapp/xlform/src/view.row.coffee
=> OC-12061, OC-11964

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, jsapp/js/components/modalForms/projectSettings.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/xlform/src/view.row.coffee
=> Fix new server deploy problem, OC-12146, and OC-12061

kobo/settings/base.py, kobo/settings/prod.py, oc/views.py
=> Fixed deployment problem

jsapp/xlform/src/view.row.coffee, kobo/settings/base.py, oc/views.py
=> OC-12140 and Fixed deployment issue

jsapp/scss/stylesheets/partials/form_builder/_card_multichoice.scss, jsapp/scss/stylesheets/partials/form_builder/_survey_row.scss, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.choices.coffee, jsapp/xlform/src/view.choices.templates.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee, kobo/settings/base.py, kpi/models/asset.py, oc/middleware.py
=> OC-12128, OC-12211, OC-12049, OC-12134, OC-12202, OC-12224, OC-12271, OC-11944, OC-12279

kobo/settings/base.py
=> Fixed CORS configuration.

jsapp/xlform/src/view.row.coffee
=> OC-12274, OC-12276

jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.surveyApp.coffee
=> OC-12140, OC-12306, OC-12295

jsapp/js/components/header.es6, jsapp/js/utils.es6, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee, kpi/urls.py, oc/views.py, package.json
Nested items between two non repeating groups are not getting auto-populated correctly
=> OC-12277, OC-12330, OC-12316, OC-12373

jsapp/js/stores.es6, kpi/views.py, oc/views.py
=> OC 1.0.x: OC-12377

jsapp/js/components/assetrow.es6, jsapp/js/components/librarySidebar.es6, jsapp/js/components/searchcollectionlist.es6, jsapp/js/ui.es6
=> OC-12481, OC-12488, OC-12519

jsapp/js/components/assetrow.es6, jsapp/js/components/searchcollectionlist.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/main.es6, jsapp/js/utils.es6, jsapp/scss/components/_kobo.collection-asset-list.scss, jsapp/scss/components/_kobo.form-builder.scss, jsapp/xlform/src/view.choices.coffee, jsapp/xlform/src/view.mandatorySetting.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.utils.coffee
=> OC-12190, OC-12489, OC-12387, OC-12518

jsapp/js/components/assetrow.es6, jsapp/js/editorMixins/assetNavigator.es6, jsapp/scss/components/_kobo.collection-asset-list.scss
=> OC-12488, OC-12570

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, jsapp/js/app.es6, jsapp/js/components/assetrow.es6, jsapp/js/components/drawer.es6, jsapp/js/components/searchcollectionlist.es6, jsapp/js/lists/library.es6, jsapp/scss/components/_kobo.form-builder.scss, jsapp/xlform/src/view.choices.coffee, jsapp/xlform/src/view.rowDetail.coffee, kpi/filters.py, kpi/models/asset.py, kpi/serializers.py
=> OC-12597, OC-12378, OC-12617, OC-12619, OC-12644, OC-12616, OC-12603

jsapp/scss/components/_kobo.form-builder.scss, jsapp/xlform/src/view.rowDetail.coffee
=> OC-12598, OC-12603

jsapp/js/components/assetrow.es6, jsapp/scss/components/_kobo.form-builder.scss, jsapp/scss/libs/react-select.overrides.scss
=> OC-12688, OC-12689, OC-12602

jsapp/js/components/librarySidebar.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/lists/library.es6, jsapp/js/utils.es6
=> OC-12687, OC-12602

jsapp/js/components/librarySidebar.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/scss/components/_kobo.modal.scss, jsapp/xlform/src/view.row.coffee
=> OC-12721, OC-12771, OC-12773

jsapp/xlform/src/view.rowDetail.coffee
=> OC-12722, OC-12841

jsapp/js/editorMixins/editableForm.es6, jsapp/xlform/src/view.rowDetail.coffee
=> OC-12722, OC-12841, OC-12840, OC-12868

jsapp/js/editorMixins/editableForm.es6, jsapp/js/mixins.es6, jsapp/js/utils.es6, jsapp/scss/components/_kobo.form-builder.scss, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.surveyApp.coffee, kpi/views.py
=> OC-12899, OC-11938, OC-12722, OC-12841, OC-12900, OC-12966, OC-12968

jsapp/js/components/drawer.es6, jsapp/xlform/src/view.rowDetail.coffee
=> OC-12358, OC-12595

jsapp/xlform/src/view.surveyApp.coffee, kpi/models/asset.py
=> OC-11938, OC-12900

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, jsapp/xlform/src/view.surveyApp.coffee
Access to Library Management is denied for certain admin users.
=> OC-13022, OC-13026

jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee
=> OC-13052, OC-13081, OC-13078, OC-13079, OC-13084

jsapp/js/utils.es6, jsapp/xlform/src/view.rowDetail.coffee, kobo/settings/base.py, kpi/models/asset.py, oc_hack/migrations/0001_alter_auth_user_username.py, oc_hack/models.py
=> OC-13642, OC-13680, OC-13682, OC-13683, and OC-12627

jsapp/js/editorMixins/editableForm.es6, jsapp/xlform/src/view.rowDetail.coffee, kobo/settings/base.py, kpi/constants.py, kpi/models/asset.py, kpi/renderers.py, kpi/views.py
=> OC-12092, OC-13692, OC-13697, OC-13701, and OC-13441

jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.surveyApp.coffee, kpi/models/asset.py
=> OC-13680, OC-13132, OC-12627, and OC-13031

jsapp/xlform/src/model.survey.coffee, jsapp/xlform/src/view.rowDetail.coffee, kpi/models/asset.py
=> OC-13108, OC-13441, OC-13750, and OC-13776

jsapp/scss/stylesheets/partials/form_builder/_card.scss, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/model.survey.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.rowSelector.coffee, kpi/models/asset.py, scripts/check-nginx/check-nginx.sh, scripts/check-nginx/install_script.sh, scripts/check-nginx/uninstall_script.sh
=> OC-13441, OC-14016, OC-13977, OC-14018

kpi/models/asset.py, scripts/check-nginx/check-nginx.sh, scripts/check-nginx/install_script.sh
=> OC-13108, OC-13977

jsapp/scss/stylesheets/partials/form_builder/_card.scss, jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/xlform/src/view.rowDetail.coffee, kpi/models/asset.py, kpi/urls.py, oc/views.py, package.json
=> OC-14425, OC-14435, OC-13897, OC-14467, OC-14516

jsapp/xlform/src/view.rowDetail.coffee
=> OC-14435, OC-14611

jsapp/js/editorMixins/editableForm.es6, jsapp/js/models/surveyScope.es6, jsapp/scss/components/_kobo.form-builder.scss, jsapp/scss/stylesheets/partials/_icons.scss, jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/scss/stylesheets/partials/form_builder/_group.scss, jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.surveyApp.coffee
=> OC-14942, OC-15046, OC-12842, OC-12843, OC-12844

jsapp/js/bem.es6, jsapp/js/components/assetrow.es6, jsapp/js/components/searchcollectionlist.es6, jsapp/js/lists/library.es6, jsapp/js/models/surveyScope.es6, jsapp/js/stores.es6, jsapp/scss/components/_kobo.collection-asset-list.scss, jsapp/scss/stylesheets/partials/form_builder/_card.scss, jsapp/scss/stylesheets/partials/form_builder/_group.scss, jsapp/xlform/src/view.choices.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.surveyApp.coffee, jsapp/xlform/src/view.utils.coffee, package.json
=> OC-14942, OC-15243, OC-15324, OC-14939, OC-12571, OC-15327, OC-12839, OC-12838

kobo/settings/base.py
=> Support openclinica-staging-2.io domain to fix cors issue.

jsapp/xlform/src/view.rowDetail.coffee
=> OC-17181 Unset contactdata value when External Value set to 'No'

jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee, kpi/models/asset.py
=> OC-17323 Remove column bind::oc:contactdata from Form Designer Template

jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee
=> OC-17128 New fields for Survey/Register/Offline Modes

jsapp/xlform/src/model.rowDetail.validationLogic.coffee
=> OC-16142 Removed quote on date type validation criteria value

jsapp/xlform/src/mv.skipLogicHelpers.coffee
=> OC-17386 Fixed Unexpected behavior for relevant logic

jsapp/xlform/src/model.rowDetailMixins.coffee, jsapp/xlform/src/model.utils.coffee, jsapp/xlform/src/view.row.coffee
=> OC-17741 Fixed preview form in edit mode when item name contains dash

jsapp/js/bem.es6, jsapp/js/components/assetrow.es6, jsapp/js/components/header.es6, jsapp/js/components/searchcollectionlist.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/lists/library.es6, jsapp/js/models/surveyScope.es6, jsapp/js/stores.es6, jsapp/scss/components/_kobo.collection-asset-list.scss, jsapp/scss/components/_kobo.form-builder.scss, jsapp/scss/stylesheets/partials/_icons.scss, jsapp/scss/stylesheets/partials/form_builder/_card.scss, jsapp/scss/stylesheets/partials/form_builder/_card_settings.scss, jsapp/scss/stylesheets/partials/form_builder/_group.scss, jsapp/xlform/src/model.base.coffee, jsapp/xlform/src/model.configs.coffee, jsapp/xlform/src/model.rowDetail.validationLogic.coffee, jsapp/xlform/src/model.rowDetailMixins.coffee, jsapp/xlform/src/model.utils.coffee, jsapp/xlform/src/mv.skipLogicHelpers.coffee, jsapp/xlform/src/view.choices.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.row.templates.coffee, jsapp/xlform/src/view.rowDetail.coffee, jsapp/xlform/src/view.surveyApp.coffee, jsapp/xlform/src/view.utils.coffee, kobo/settings/base.py, kpi/models/asset.py, package.json
=> [May-31-2022] Merge master into 2.1.x

Dockerfile, dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, docker/init.bash, docker/run_uwsgi.bash, kobo/urls.py, kpi/management/commands/copy_kc_profile.py, kpi/management/commands/import_from_url.py, kpi/management/commands/import_survey_drafts_from_dkobo.py, kpi/management/commands/populate_assetversions.py, kpi/management/commands/remove_deprecated_settings.py, kpi/management/commands/remove_duplicate_assetversions.py, kpi/management/commands/sync_kobocat_xforms.py, kpi/urls.py, oc/middleware.py
=> [2.1.x] OC-19137

Dockerfile, dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt, kpi/models/asset.py
1. [x] If you've added code that should be tested, add tests
2. [x] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure your code lints and you followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] If this is a big feature, make sure to prefix the title with `Feature:` and add a thorough description for non-dev folk
=> [2.1.x] OC-19137 (2)

docker/init.bash, oc_hack/migrations/0002_add_unique_constraint_user_username.py
=> OC-20038 Fixed django migration issue due to unique index error creation on auth_user

kpi/views.py
=> OC-20287 Fixed 500 error when adding Library item

kpi/views.py
=> OC-20395 Fixed FD not loading when creating new form in Form Designer

package.json
=> Updating version number for next release

package.json
=> Upgrade minimist to version 1.2.8

jsapp/js/editorMixins/editableForm.es6, jsapp/xlform/src/model.row.coffee, jsapp/xlform/src/view.rowDetail.coffee
=> OC-17484 Editing a consent form

jsapp/js/components/drawer.es6, jsapp/js/editorMixins/editableForm.es6, jsapp/js/lists/library.es6, jsapp/scss/components/_kobo.form-builder.scss
=> OC-20792 Add a Doc Site link within Form Designer/Library Management

kpi/views.py
=> OC-21267 Fixed error when creating collection

jsapp/xlform/src/model.survey.coffee
=> OC-21279 Fixed form can't be previewed if item name exceeds 36 chars

.github/workflows/pytest.yml, jsapp/js/components/formBuilder/formBuilderUtils.es6, jsapp/js/components/library/myLibraryRoute.es6, jsapp/js/dataInterface.ts, jsapp/js/editorMixins/editableForm.es6, jsapp/js/ocutils.ts, jsapp/scss/components/_kobo.form-builder.scss, jsapp/xlform/src/model.survey.coffee, kobo/settings/base.py, kobo/urls.py, kpi/serializers/v2/asset_snapshot.py, oc/settings.py
=> upstream-release-140823

Dockerfile, Jenkinsfile
=> Upstream release

jsapp/scss/main.scss, package.json
=> OC-21513 Fixed error in Skip Logic / Validation Criteria caused by select2 upgrade

jsapp/js/components/assetsTable/assetsTable.scss, jsapp/js/components/library/assetInfoBox.es6, jsapp/js/components/library/myLibraryRoute.es6, jsapp/js/dataInterface.ts, jsapp/js/editorMixins/editableForm.es6, jsapp/js/main.es6, jsapp/js/ocutils.ts, jsapp/js/stores/session.ts, jsapp/scss/main.scss, package-lock.json, package.json
=> Upstream release 130923

jsapp/js/editorMixins/editableForm.es6, jsapp/scss/components/_kobo.list-view.scss, jsapp/xlform/src/model.row.coffee, jsapp/xlform/src/model.survey.coffee, jsapp/xlform/src/view.choices.coffee, jsapp/xlform/src/view.row.coffee, jsapp/xlform/src/view.rowDetail.coffee
=> OC-17484 Fixed error messages displays for eConsent Form editing

Dockerfile, docker/init.bash
=> OC-20909 Using AWS ECR koboform_base docker image

Dockerfile, kobo/settings/base.py, kpi/deployment_backends/kc_access/utils.py, kpi/deployment_backends/kobocat_backend.py
=> [upstream-release] Merge 2.023.21 and Get CSP_ENV_SITES from env

Dockerfile, Jenkinsfile, dependencies/pip/requirements.txt
=> Upstream release with changes in docker file and repo in jenkins file

kobo/settings/base.py
=> OC-22568 Fix save failed because of CSRF trusted origin error

jsapp/xlform/src/view.row.coffee
=> OC-22741 Fixed select options and settings toggles

Dockerfile, docker/init.bash
=> Fixed kpi-build-error

kobo/settings/base.py
=> Fixed preview URL

jsapp/js/actions.es6
=> OC-22820 Fixed duplicated success message on Save Draft

jsapp/js/assetParserUtils.ts
=> OC-22822 Fixed Form ID and Form version not displayed

kobo/apps/service_health/views.py
=> OC-22844 Removed monitoring of enketo instance

jsapp/js/api.ts, jsapp/js/main.es6, kobo/settings/base.py
=> OC-22819 Changed csrftoken cookie name to occsrftoken

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt
=> OC-23589 Update boss-oidc to Update keycloak uid for existing user instead of deleting it

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt
=> OC-23859 Update kc_user UID using SQL

dependencies/pip/dev_requirements.txt, dependencies/pip/external_services.txt, dependencies/pip/requirements.in, dependencies/pip/requirements.txt
This reverts commit 6bde3c5e9db80a369ab44268072cc16ce5f033b5.
=> Revert "OC-23859 Update kc_user UID using SQL"
